LOCAL_PATH := $(call my-dir)
 include $(CLEAR_VARS)
LOCAL_MODULE := GMessaging
LOCAL_MODULE_TAGS := optional
LOCAL_SRC_FILES := prebuild/GMessaging.apk
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_MODULE_CLASS := APPS
LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)
LOCAL_MODULE_PATH := $(TARGET_OUT)/app
LOCAL_OVERRIDES_PACKAGES := messaging
include $(BUILD_PREBUILT) 
